version: '3.8'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=PASSWORD1234
  
  user-project:
    build: 
      dockerfile: dockerfile
      context: ./
    
    ports:
      - 3000:3000
    
    environment:
      - DATABASE_URL=postgresql://postgres:PASSWORD1234@postgres:5432/postgres

    depends_on:
      - postgres
